<?php
DEFINE('DB_CONNECTION', 'mysql:host=10.5.250.41;port=3306;dbname=scalr');
DEFINE('DB_USER', 'scalr');
DEFINE('DB_PASSWORD', 'sc@lrpass');
DEFINE('ENVIORNMENT', 'PROD');
DEFINE('LOG_PATH', '/var/www/rajamani/log/');
-DEFINE('opsEmail','itcloudops@adobe.com');
-DEFINE('devEmail','itc-dev@adobe.com');
-DEFINE('Email','itcadmin@adobe.com');
-DEFINE('adminEmail','itc-dev@adobe.com');
DEFINE('CRYPT_ALGO', 'rijndael-256');
DEFINE('ENCRYPTION_KEY', 'cc07a428de33fe05c27c316927bd15d1');
DEFINE('ENDPOINT_URL', serialize(array( 'url' => array( 'San Jose' => 'https://s3-sj1.corp.adobe.com'),
    'port' => array('admin' => '19443'))));
DEFINE('USER', '');
DEFINE('PASS', '');
DEFINE('SSH_KEY_PATH', '/tmp/privkey.pem');
DEFINE('GRPMGR_API_KEY', '');
DEFINE('NFS_USER', '');
DEFINE('NFS_BACKUP_EMAIL', '');
DEFINE('NFS_API_URL', '');
DEFINE('STORAGE_URL', '');
DEFINE('CIFS_USER', 'stgauto@da1isi101.corp.adobe.com');
DEFINE('SCALR_PATH', '/var/www/scalr.net-trunk/');
DEFINE('MESOS_API_URL','https://itcapi.paas-stg.corp.adobe.com/');
DEFINE('MESOS_API_URL2','https://itcapi.paas-stg.corp.adobe.com/');
#DEFINE('MESOS_API_URL2','https://mesos-broker2.paas-stg.corp.adobe.com/');
DEFINE('MESOS_API_USERNAME','rajamani');
DEFINE('MESOS_API_PASSWORD','TMv$e9#nU*7Y');
DEFINE('MESOS_API_PROJECT', 'RajamaniDev');
DEFINE('CAMP_API_URL','https://itc-compute-dev-4.corp.adobe.com/amp/api');
DEFINE('CAMP_API_USERNAME','8c0c72d2729944ce6ac3fe63e0cfe8e7');
DEFINE('CAMP_API_PASSWORD','5b775f2f5a62932839beb79151876fd1');
DEFINE('UPLOAD_LOCATION','/var/upload/');
DEFINE('CIFS_BACKUP_EMAIL','rajamani@adobe.com');
DEFINE('CIFS_API_URL','https://itcapi.paas-stg.corp.adobe.com/cifs/v1/exports');
DEFINE('CAMP_CIFSAPI_CLIENT_ID', '25a88391d61b5d9603cf3b3584459e20');
DEFINE('CAMP_CIFSAPI_CLIENT_SECRET', 'REn$d3#yL*$h#Cm#B');
DEFINE('DOC_PATH', '');
DEFINE('base_url'     , 'http://itcportal-dev.corp.adobe.com/rajamani/mesos/');
DEFINE('index_page' , '');
DEFINE('uri_protocol' , 'AUTO');
DEFINE('url_suffix' , '');
DEFINE('language'     , 'english');
DEFINE('charset' , 'UTF-8');
DEFINE('enable_hooks' , FALSE);
DEFINE('subclass_prefix' , 'MY_');
DEFINE('permitted_uri_chars' , 'a-zA-Z0-9@~%.:_\-\#');
DEFINE('allow_get_array'              , TRUE);
DEFINE('enable_query_strings' , FALSE);
DEFINE('controller_trigger'   , 'c');
DEFINE('function_trigger'             , 'm');
DEFINE('directory_trigger'    , 'd'); // experimental not currently in use
DEFINE('log_threshold' , 0);
DEFINE('log_path' , '');
DEFINE('log_date_format', 'Y-m-d H:i:s');
DEFINE('cache_path', '');
DEFINE('encryption_key', 'F4CCJJUGWU97');
DEFINE('sess_cookie_name'             , 'ci_session');
DEFINE('sess_expiration'              , 7200);
DEFINE('sess_expire_on_close' , FALSE);
DEFINE('sess_encrypt_cookie'  , FALSE);
DEFINE('sess_use_database'    , FALSE);
DEFINE('sess_table_name'              , 'ci_sessions');
DEFINE('sess_match_ip'                , FALSE);
DEFINE('sess_match_useragent' , TRUE);
DEFINE('sess_time_to_update'  , 300);
DEFINE('cookie_prefix'        , "");
DEFINE('cookie_domain'        , "");
DEFINE('cookie_path'          , "/");
DEFINE('cookie_secure'        , FALSE);
DEFINE('global_xss_filtering' , FALSE);
DEFINE('csrf_protection' , FALSE);
DEFINE('csrf_token_name' , 'csrf_test_name');
DEFINE('csrf_cookie_name' , 'csrf_cookie_name');
DEFINE('csrf_expire' , 7200);
DEFINE('compress_output' , FALSE);
DEFINE('time_reference' , 'local');
DEFINE('rewrite_short_tags' , FALSE);
DEFINE('proxy_ips' , '');
DEFINE('doc_url' , '');
?>
