<?php
DEFINE('DB_CONNECTION', '');
DEFINE('DB_USER', '');
DEFINE('DB_PASSWORD', '');
DEFINE('ENVIORNMENT', '');
DEFINE('LOG_PATH', '');
DEFINE('OPENSTACK_PROVIDER', '');
DEFINE('OPENSTACK_ACCESS_URL', '');
DEFINE('ENCRYPTION_KEY', '');
DEFINE('opsEmail','myself@none.com');
DEFINE('devEmail','myself@none.com');
DEFINE('Email','myself@none.com');
DEFINE('adminEmail','myself@none.com');
DEFINE('GRPMGR_API_KEY', '');
DEFINE('SCALR_PATH', '');
DEFINE('CAMP_API_URL','');
DEFINE('CAMP_API_USERNAME','');
DEFINE('CAMP_API_PASSWORD','');
DEFINE('base_url'     ,'');
DEFINE('index_page' , '');
DEFINE('uri_protocol' , 'AUTO');
DEFINE('url_suffix' , '');
DEFINE('language'     , 'english');
DEFINE('charset' , 'UTF-8');
DEFINE('enable_hooks' , FALSE);
DEFINE('subclass_prefix' , 'MY_');
DEFINE('permitted_uri_chars' , 'a-zA-Z0-9@~%.:_\-\#');
DEFINE('allow_get_array'              , TRUE);
DEFINE('enable_query_strings' , FALSE);
DEFINE('controller_trigger'   , 'c');
DEFINE('function_trigger'             , 'm');
DEFINE('directory_trigger'    , 'd'); 
DEFINE('log_threshold' , 0);
DEFINE('log_path' , '');
DEFINE('log_date_format', 'Y-m-d H:i:s');
DEFINE('cache_path', '');
DEFINE('encryption_key', '');
DEFINE('sess_cookie_name'             , 'ci_session');
DEFINE('sess_expiration'              , 7200);
DEFINE('sess_expire_on_close' , FALSE);
DEFINE('sess_encrypt_cookie'  , FALSE);
DEFINE('sess_use_database'    , FALSE);
DEFINE('sess_table_name'              , 'ci_sessions');
DEFINE('sess_match_ip'                , FALSE);
DEFINE('sess_match_useragent' , TRUE);
DEFINE('sess_time_to_update'  , 300);
DEFINE('cookie_prefix'        , "");
DEFINE('cookie_domain'        , "");
DEFINE('cookie_path'          , "/");
DEFINE('cookie_secure'        , FALSE);
DEFINE('global_xss_filtering' , FALSE);
DEFINE('csrf_protection' , FALSE);
DEFINE('csrf_token_name' , 'csrf_test_name');
DEFINE('csrf_cookie_name' , 'csrf_cookie_name');
DEFINE('csrf_expire' , 7200);
DEFINE('compress_output' , FALSE);
DEFINE('time_reference' , 'local');
DEFINE('rewrite_short_tags' , FALSE);
DEFINE('proxy_ips' , '');
DEFINE('doc_url' , '');
?>
